// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/cpu-metrics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cpu-metrics.get').default>>>>
    }
    '/api/disks-capacity-metrics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/disks-capacity-metrics.get').default>>>>
    }
    '/api/disks-metrics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/disks-metrics.get').default>>>>
    }
    '/api/main-infos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/main-infos.get').default>>>>
    }
    '/api/memory-metrics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/memory-metrics.get').default>>>>
    }
    '/api/network-metrics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/network-metrics.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}