version: '3.8'

services:
  metricsminder:
    image: thomasleconte/metricsminder:latest
    container_name: metricsminder
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
